version: "3.9"
services:
    prediction_app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-prediction
        network_mode: "host"
    #    depends_on:
    #      - "decision_app"
    decision_app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-decision
        network_mode: "host"
    monitor_app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-monitor
        network_mode: "host"
        depends_on:
            - "prediction_app"
        environment:
            - DBAAS_SERVICE_HOST=localhost
            - DBAAS_SERVICE_PORT=6379
    miniserve_app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-miniserve
        network_mode: "host"
    redis:
        image: "redis:alpine"
