version: "3.9"
services:
    prediction_app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-prediction
        #image: prediction-xapp:latest
        network_mode: "host"
        depends_on:
          - "decision_app"

    decision_app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-decision
        #image: decision-xapp:latest
        network_mode: "host"

